version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - C:/Users/002/Desktop/cook-cache/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cook_admin
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - C:/Users/002/Desktop/cook-cache/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
